package:
  name: "g2o-python"
  version: "0.0.2"

source:
  git_rev: 0.0.2
  git_url: https://github.com/miquelmassot/g2o-python

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - numpy
    - cython

about:
  home: https://github.com/miquelmassot/g2o-python
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Wrapper for g2o python bindings"

extra:
  recipe-maintainers:
    - miquelmassot
