name: CI
on: [push]

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: base
          environment-file: environment.yml
      - name: Install the package
        run: |
          pip install -U --user .
